export const DEFAULT_GRID_MAX_WIDTH = 672;

export const ELEMENT_TYPES = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  GRID: 'GRID',
};

export const VERTICAL_RESIZE_TYPES = [
  ELEMENT_TYPES.IMAGE,
  ELEMENT_TYPES.GRID,
];